version: "3.9"

services:
  django:
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:${DOCKER_TAG}
    container_name: django_con
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - ./:/srv/PleaseGraduate/deploy
      - ../db.sqlite3:/srv/PleaseGraduate/db.sqlite3  # SQLite DB 영구 저장
    command: bash docker_cmd.sh prod
